name: Multiply Numbers Workflow

on: [push]

jobs:
  multiply_numbers:
    name: Multiply Numbers
    runs-on: ubuntu-latest

    needs: add_numbers

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Run JavaScript Script
        id: multiply
        run: |
          add_result=${{ needs.add_numbers.outputs.result }}
          result=$(echo "$((add_result * 3))")
          echo "::set-output name=result::$result"
